# Generated by Django 2.0 on 2020-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mobile_no', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('gst_no', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
