# Generated by Django 2.0 on 2020-08-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
