# Generated by Django 2.2 on 2020-08-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0002_auto_20200803_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='destination',
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
