# Generated by Django 2.0 on 2020-08-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0002_auto_20200802_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=60),
        ),
    ]
