# Generated by Django 2.2 on 2020-08-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0003_auto_20200804_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.IntegerField(max_length=60),
        ),
    ]
