# Generated by Django 2.0 on 2020-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0003_auto_20200802_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=15),
        ),
    ]
