# Generated by Django 2.0 on 2020-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0004_auto_20200802_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(max_length=60),
        ),
    ]
