# Generated by Django 2.2 on 2020-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0004_auto_20200804_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
