# Generated by Django 2.2 on 2020-08-10 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0004_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='destination',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amyra.Destination'),
        ),
    ]
