# Generated by Django 2.2 on 2020-08-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0005_auto_20200804_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('bill_type', models.CharField(max_length=500, null=True)),
                ('invoice_no', models.CharField(max_length=500, null=True)),
                ('hsn_code', models.CharField(max_length=4)),
                ('dated', models.DateField()),
                ('transport', models.CharField(max_length=500, null=True)),
                ('vehicle_no', models.CharField(max_length=500, null=True)),
                ('challan_no', models.CharField(max_length=500, null=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='amyra.Customer')),
            ],
        ),
    ]
