# Generated by Django 2.2 on 2020-08-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0006_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amyra.Customer'),
        ),
    ]
