# Generated by Django 2.2 on 2020-08-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0009_calculation_igst'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='total_amount_after_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
