# Generated by Django 2.2 on 2020-08-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyra', '0010_calculation_total_amount_after_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='total_amount_in_words',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
